/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:d758649a-9a99-42a9-8447-5759f7c8a7f6", // The identity pool provisioned by Amplify CLI as part of Amplify Push Notification setup (not by CDK)
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_43U1iUNGn", // Metmos - CDK managed
    "aws_user_pools_web_client_id": "7ntos3ij1oasim7h2lrfkhpu8n", // Metmos - CDK managed 
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": ['Google', 'Facebook'],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "6ac4c860e78f439da68e70a11f90588c", // managed by Amplify CLI
    "aws_mobile_analytics_app_region": "ap-southeast-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "6ac4c860e78f439da68e70a11f90588c", // managed by Amplify CLI
            "region": "ap-southeast-2"
        }
    },
    "Notifications": {
        "Push": {
            "AWSPinpoint": {
                "appId": "6ac4c860e78f439da68e70a11f90588c", // managed by Amplify CLI
                "region": "ap-southeast-2"
            }
        }
    },
    "oauth": {
        "domain": "metmos-staging.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code",
        "providers": ['Google', 'Facebook'],
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "Auth": {
        "Cognito": {
            "userPoolId": "ap-southeast-2_43U1iUNGn",
            "userPoolClientId": "7ntos3ij1oasim7h2lrfkhpu8n",
            "identityPoolId": "ap-southeast-2:d758649a-9a99-42a9-8447-5759f7c8a7f6"
        }
    },
};


export default awsmobile;
